"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import { Box, CssBaseline } from "@mui/material";
import theme from "./theme";
import ThemeProvider from "@/theme";
import Header from "@/components/Header";

import axiosInstance from "@/utils/axios";

import { DragDropContext } from "react-beautiful-dnd";
import { clickedEnum } from "@/utils/atom";
import { useRecoilValue } from "recoil";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const onDragEnd = (result) => {
    const { source, destination } = result;

    // 드롭 지점이 없거나, 같은 위치로 이동한 경우 아무것도 하지 않음
    if (
      !destination ||
      (source.droppableId === destination.droppableId &&
        source.index === destination.index)
    ) {
      return;
    }

    // 사이드바 리스트에서 테이블로 아이템을 이동했는지 확인
    if (
      source.droppableId === `sidebarList-/course/simulate` &&
      destination.droppableId === "customTable"
    ) {
      console.log("!!!!!@#!@#!@#!@");
      // 여기서 API 호출 로직 구현
      // axiosInstance
      //   .post("/user/addPlanLecture/tableId/courseId/enum", {
      //     // 필요한 데이터 전송
      //   })
      //   .then((response) => {
      //     // 성공 처리

      //   })
      //   .catch((error) => {
      //     // 에러 처리
      //   });
    }
  };

  return (
    <html lang="en">
      <ThemeProvider>
        <DragDropContext onDragEnd={onDragEnd}>
          <CssBaseline />
          <body className={inter.className}>
            <Header />

            {children}
          </body>
        </DragDropContext>
      </ThemeProvider>
    </html>
  );
}
